### ISSUE TITLE
Android Studio is .......

### ISSUE THREAD

**Issue by devilcloner** [aws1994/MovieUiTemplate#2]
indicator.setupWithViewPager(sliderpager,true); 
Android Studio is not accepting this "
![error](https://user-images.githubusercontent.com/50172974/57019151-42c00580-6c43-11e9-9992-618142a18bda.PNG)
setupWithViewPager"

**Comment by aws1994** [comment]
private TabLayout indicator;
indicator is type of TabLayout not TableLayout

**Comment by devilcloner** [comment]
Thank you very much sir .

**Comment by devilcloner** [comment]
You made my day sir .
